# Generated by Django 2.2.3 on 2019-07-19 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purse_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeBudgetLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseBudgetLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='income',
            name='budget_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purse_app.IncomeBudgetLine'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='budget_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purse_app.PurchaseBudgetLine'),
        ),
    ]
