# Generated by Django 2.2.3 on 2019-07-19 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purse_app', '0002_auto_20190719_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='budget_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purse_app.IncomeBudgetLine', to_field='line'),
        ),
        migrations.AlterField(
            model_name='incomebudgetline',
            name='line',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='budget_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purse_app.PurchaseBudgetLine', to_field='line'),
        ),
        migrations.AlterField(
            model_name='purchasebudgetline',
            name='line',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
