# Generated by Django 2.2.3 on 2019-07-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purse_app', '0003_auto_20190719_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_debit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_credit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
