# Generated by Django 2.2.3 on 2019-07-30 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purse_app', '0009_auto_20190730_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcards',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='debitcards',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='incomebudgetline',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='othercredits',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='otherdebits',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='purchasebudgetline',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='summary',
            old_name='user',
            new_name='owner',
        ),
    ]
