# Generated by Django 2.2.3 on 2019-08-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purse_app', '0011_auto_20190730_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcards',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='debitcards',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.RemoveField(
            model_name='income',
            name='budget_line',
        ),
        migrations.AddField(
            model_name='income',
            name='budget_line',
            field=models.ManyToManyField(to='purse_app.IncomeBudgetLine'),
        ),
        migrations.RemoveField(
            model_name='income',
            name='to_debit_card',
        ),
        migrations.AddField(
            model_name='income',
            name='to_debit_card',
            field=models.ManyToManyField(blank=True, null=True, to='purse_app.DebitCards'),
        ),
        migrations.AlterField(
            model_name='incomebudgetline',
            name='line',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='othercredits',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='otherdebits',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='budget_line',
        ),
        migrations.AddField(
            model_name='purchase',
            name='budget_line',
            field=models.ManyToManyField(to='purse_app.PurchaseBudgetLine'),
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='with_credit_card',
        ),
        migrations.AddField(
            model_name='purchase',
            name='with_credit_card',
            field=models.ManyToManyField(blank=True, null=True, to='purse_app.CreditCards'),
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='with_debit_card',
        ),
        migrations.AddField(
            model_name='purchase',
            name='with_debit_card',
            field=models.ManyToManyField(blank=True, null=True, to='purse_app.DebitCards'),
        ),
        migrations.AlterField(
            model_name='purchasebudgetline',
            name='line',
            field=models.CharField(max_length=40),
        ),
    ]
