# Generated by Django 2.2.3 on 2019-08-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purse_app', '0012_auto_20190809_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='to_debit_card',
            field=models.ManyToManyField(blank=True, to='purse_app.DebitCards'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='with_credit_card',
            field=models.ManyToManyField(blank=True, to='purse_app.CreditCards'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='with_debit_card',
            field=models.ManyToManyField(blank=True, to='purse_app.DebitCards'),
        ),
    ]
