# Generated by Django 2.2.3 on 2019-08-09 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purse_app', '0013_auto_20190809_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcards',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='debitcards',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.RemoveField(
            model_name='income',
            name='budget_line',
        ),
        migrations.AddField(
            model_name='income',
            name='budget_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purse_app.IncomeBudgetLine', to_field='line'),
        ),
        migrations.RemoveField(
            model_name='income',
            name='to_debit_card',
        ),
        migrations.AddField(
            model_name='income',
            name='to_debit_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purse_app.DebitCards', to_field='name'),
        ),
        migrations.AlterField(
            model_name='incomebudgetline',
            name='line',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='othercredits',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='otherdebits',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='budget_line',
        ),
        migrations.AddField(
            model_name='purchase',
            name='budget_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purse_app.PurchaseBudgetLine', to_field='line'),
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='with_credit_card',
        ),
        migrations.AddField(
            model_name='purchase',
            name='with_credit_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purse_app.CreditCards', to_field='name'),
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='with_debit_card',
        ),
        migrations.AddField(
            model_name='purchase',
            name='with_debit_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purse_app.DebitCards', to_field='name'),
        ),
        migrations.AlterField(
            model_name='purchasebudgetline',
            name='line',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
